name: Assign New Issues

on:
  issues:
    types: 
      - opened

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: actions-ecosystem/action-assign@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: team-member-username # Replace with the GitHub username of the team member
